services:
  - docker

before_install:
  - docker build -t danilucaci/react-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danilucaci/react-tests npm run test -- --coverage

after_success:
  - docker build -t danilucaci/multi-client ./client
  - docker build -t danilucaci/multi-nginx ./nginx
  - docker build -t danilucaci/multi-server ./server
  - docker build -t danilucaci/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # push the images to the docker hub
  - docker push danilucaci/multi-client
  - docker push danilucaci/multi-nginx
  - docker push danilucaci/multi-server
  - docker push danilucaci/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-west-1"
#   app: "multiple-services"
#   env: "Reactapp"
#   bucket_name: "elasticbeanstalk-eu-west-1-450943128072"
#   bucket_path: "multiple-services"
#   on:
#     branch: main
#   access_key_id: "$AWS_ACCESS_KEY"
#   secret_access_key: "$AWS_SECRET_KEY"

language: generic
